Repository nnmrts/starfield-efm, pull requests merged in 2024-11, with the labels that each got.

#5 refactor build process
  build.bat
  deploy-to-game.bat
  deploy-to-mo2.bat
  dist/interface/favoritesmenu Report.txt
  interface/EFM.FavoritesMenu/FavoritesMenu.as
  interface/EFM.FavoritesMenu/FavoritesMenu.fla/PublishSettings.xml
  interface/deploy.bat
  plugins/efm.esm
  scripts/EFM.ppj
  scripts/build.bat
Labels: size/L

#8 Allow fonts_en publish report
  .gitignore
  dist/interface/fonts_en Report.txt
Labels: size/M

#11 Sync `testing-events` with `main`
  .vscode/settings.json
Labels: size/XS

#12 Sync `scrivener-exp` with `testing-events`
  .vscode/settings.json
  interface/Adobe/com/adobe/serialization/json/JSONDecoder.as
  interface/Adobe/com/adobe/serialization/json/JSONParseError.as
  interface/Adobe/com/adobe/serialization/json/JSONToken.as
  interface/Adobe/com/adobe/serialization/json/JSONTokenType.as
  interface/Adobe/com/adobe/serialization/json/JSONTokenizer.as
  interface/Bethesda/Components/ImageFixture.as
  interface/Bethesda/Shared/AS3/BSDisplayObject.as
  interface/Bethesda/Shared/AS3/Data/BSUIDataManager.as
  interface/Bethesda/Shared/AS3/Data/BSUIEventDispatcherBackend.as
  interface/Bethesda/Shared/AS3/Data/FromClientDataEvent.as
  interface/Bethesda/Shared/AS3/Data/TestProviderLoader.as
  interface/Bethesda/Shared/AS3/Data/UIDataFromClient.as
  interface/Bethesda/Shared/AS3/Data/UIDataShuttleConnector.as
  interface/Bethesda/Shared/AS3/Data/UIDataShuttleTestConnector.as
  interface/Bethesda/Shared/AS3/Data/UsesEventDispatcherBackend.as
  interface/Bethesda/Shared/AS3/Events/CustomEvent.as
  interface/Bethesda/Shared/AS3/IMenu.as
  interface/Bethesda/Shared/Components/ContentLoaders/BaseLoaderClip.as
  interface/Bethesda/Shared/Components/ContentLoaders/ImageLoaderClip.as
  interface/Bethesda/Shared/Components/ContentLoaders/SymbolLoaderClip.as
  interface/Bethesda/Shared/EnumHelper.as
  interface/Bethesda/Shared/GlobalFunc.as
  interface/Bethesda/Shared/InventoryItemUtils.as
  interface/Bethesda/Shared/PlatformUtils.as
  interface/Bethesda/scaleform/gfx/DisplayObjectEx.as
  interface/Bethesda/scaleform/gfx/Extensions.as
  interface/Bethesda/scaleform/gfx/InteractiveObjectEx.as
  interface/Bethesda/scaleform/gfx/TextFieldEx.as
  interface/EFM.FavoritesMenu/FavoritesMenu.as
Labels: size/XXL
